version: "3.2"
services: 
    web:
        ports: 
            - "3000:3000"
        build:
            context: .
            dockerfile: Dockerfile.dev
        environment: 
            - CHOKIDAR_USEPOLLING=true
        volumes: 
            - /app/node_modules
            - .:/app
        stdin_open: true
    
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        environment: 
            - CHOKIDAR_USEPOLLING=true
        volumes: 
            - /app/node_modules
            - .:/app
        stdin_open: true
        command: ["npm", "run", "test"]
            